import { z } from 'zod';

const manifestProvisioningConfigSchema = z.object({
  configToken: z.string().min(1),
});

export type ManifestProvisioningConfig = z.infer<
  typeof manifestProvisioningConfigSchema
>;

export type ParseManifestProvisioningConfigResult =
  | { readonly ok: true; readonly config: ManifestProvisioningConfig }
  | {
      readonly ok: false;
      readonly error: {
        readonly kind: 'invalid-config';
        readonly issues: readonly string[];
      };
    };

/**
 * Pure boundary parser — same `parsePersonaConfig`/`parseGithubConfig` shape and precedent. The
 * app configuration token is manually generated by Alex at api.slack.com/apps (12-hour expiry,
 * refreshable via `tooling.tokens.rotate`, but a one-shot provisioning run of 7 apps at ~1/min
 * finishes in minutes — rotation isn't wired here, only needed if this ever becomes a
 * long-running/repeated tool rather than a one-shot script).
 */
export function parseManifestProvisioningConfig(
  env: Readonly<Record<string, string | undefined>>,
): ParseManifestProvisioningConfigResult {
  const parsed = manifestProvisioningConfigSchema.safeParse({
    configToken: env.MOE_SLACK_APP_CONFIG_TOKEN,
  });

  return parsed.success
    ? { ok: true, config: parsed.data }
    : {
        ok: false,
        error: {
          kind: 'invalid-config',
          issues: parsed.error.issues.map(
            (issue) => `${issue.path.join('.')}: ${issue.message}`,
          ),
        },
      };
}
